### ISSUE TITLE
Mobile view is so bad :(

### ISSUE THREAD

**Issue by aml987** [GavickPro/Magazine-Free-Joomla-Template#10]
www.sycourse.com , How can I delete the social bar from mobile view? 

---

https://www.dropbox.com/s/f1h1txm1ej3j73i/Screenshot_2014-05-31-21-53-38.png
https://www.dropbox.com/s/ng47dn8su9iz7ze/Screenshot_2014-05-30-10-17-25.png

**Comment by bkrztuk** [comment]
Please add to override.css file this code : 

``` css
#gkToolbar { display: none }
```

**Comment by aml987** [comment]
Please check my site: the tool-bar still exist http://www.sycourse.com/ 
anyway how can I display it from mobile view only?.. thank you....

**Comment by aml987** [comment]
There is many problem with mobile view, Can I display all the modules and the menu from mobile view?

**Comment by bkrztuk** [comment]
If you want to hide this bar only on **mobile** view please add this code to mobile.css file : 

``` css
#gkToolbar { display: none }
body { margin: 0 !important }
```

It is also necessary to hide jump to top button in mobile view when the sidebar is not active by adding code to mentioned file : 

``` css
#gkBackToTop { display: none }
```
